name: Security - Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches-ignore: ["main"]
  schedule:
    - cron: "20 17 * * *"

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    timeout-minutes: 480
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP }}
